"use client";

import { useRef } from "react";
import { ImageIcon, Info } from "lucide-react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";

import {
  Field,
  FieldError,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { RequiredFieldLabel } from "@/components/RequiredFieldLabel";
import { AutoGeneratedSlugField } from "@/components/forms/fields/AutoGeneratedSlugField";
import { LogoUploadField } from "@/components/forms/fields/LogoUploadField";
import {
  CreateCategoryFormValues,
  createCategorySchema,
} from "@/features/categories/schemas";

interface CategoryFormProps {
  onSubmit: (values: CreateCategoryFormValues) => void;
  defaultValues?: Partial<CreateCategoryFormValues>;
  isSubmitting?: boolean;
}

export function CategoryForm({ onSubmit, defaultValues }: CategoryFormProps) {
  const slugTouched = useRef(false);

  const form = useForm<CreateCategoryFormValues>({
    resolver: zodResolver(createCategorySchema),
    defaultValues,
    mode: "all",
  });

  const {
    register,
    handleSubmit,
    setValue,
    formState: { errors },
  } = form;

  return (
    <form
      onSubmit={handleSubmit(onSubmit)}
      className="space-y-4"
      id="category-form"
    >
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Info size={16} /> Basic details
          </CardTitle>
        </CardHeader>
        <CardContent>
          <FieldGroup>
            <div className="grid grid-cols-2 gap-4">
              <Field>
                <RequiredFieldLabel htmlFor="name">
                  Category name
                </RequiredFieldLabel>
                <Input
                  id="name"
                  placeholder="Smartphone"
                  {...register("name")}
                  aria-invalid={!!errors.name}
                />
                <FieldError>{errors.name?.message}</FieldError>
              </Field>

              <AutoGeneratedSlugField
                form={form}
                slugTouchedRef={slugTouched}
              />
            </div>

            <Field>
              <FieldLabel htmlFor="parentCategory">Parent category</FieldLabel>
              <Select
                onValueChange={(value) =>
                  setValue("parentId", value, { shouldDirty: true })
                }
              >
                <SelectTrigger id="parentCategory">
                  <SelectValue placeholder="Select parent category" />
                </SelectTrigger>
                <SelectContent>
                  <SelectGroup>
                    <SelectItem value="138fda19-1822-4866-8b37-1112990af009">
                      Apple
                    </SelectItem>
                    <SelectItem value="e7ee8d5c-3353-4e84-a566-879bca368ea5">
                      Samsung
                    </SelectItem>
                    <SelectItem value="9b417a6b-8097-4675-b29c-6e7a5c3613ff">
                      Lenovo
                    </SelectItem>
                  </SelectGroup>
                </SelectContent>
              </Select>
            </Field>

            <Field>
              <FieldLabel htmlFor="description">Description</FieldLabel>
              <Textarea
                id="description"
                placeholder="Type the description here"
                className="min-h-30"
                {...register("description")}
              />
            </Field>
          </FieldGroup>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <ImageIcon size={16} /> Media
          </CardTitle>
        </CardHeader>

        <CardContent>
          <LogoUploadField form={form} />
        </CardContent>
      </Card>
    </form>
  );
}
