"use client";

import { ImageIcon, Info } from "lucide-react";
import { useEffect } from "react";
import { Controller, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { toast } from "sonner";

import { Category } from "../types";
import { RichTextEditor } from "@/components/editor/RichTextEditor";
import { AutoGeneratedSlugField } from "@/components/forms/fields/AutoGeneratedSlugField";
import { LogoUploadField } from "@/components/forms/fields/LogoUploadField";
import { RequiredFieldLabel } from "@/components/RequiredFieldLabel";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Field,
  FieldError,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  CreateCategoryFormValues,
  createCategorySchema,
} from "@/features/categories/schemas";
import { Media } from "@/features/media/types";
import { getDirtyValues } from "@/utils";

interface CategoryFormProps {
  category?: Category;
  parentCategories?: Category[];
  isSubmitting?: boolean;
  onSubmit: (values: Partial<CreateCategoryFormValues>) => void;
  mediaItems?: Media[];
  isLoadingMediaItems?: boolean;
  onFetchMediaItems?: () => void;
  onUploadMediaItems?: (files: File[]) => void;
  isUploadingMediaItems?: boolean;
  onDeleteMediaItem?: (id: string) => void;
  isDeletingMediaItem?: boolean;
}

const DEFAULT_VALUES: CreateCategoryFormValues = {
  name: "",
  slug: "",
  description: undefined,
  parentId: undefined,
  logo: undefined,
  removeLogo: undefined,
};

export function CategoryForm({
  category,
  parentCategories,
  onSubmit,
  onFetchMediaItems,
  mediaItems,
  isLoadingMediaItems,
  onUploadMediaItems,
  isUploadingMediaItems,
  onDeleteMediaItem,
  isDeletingMediaItem,
}: CategoryFormProps) {
  const form = useForm<CreateCategoryFormValues>({
    resolver: zodResolver(createCategorySchema),
    defaultValues: DEFAULT_VALUES,
    mode: "all",
  });

  const {
    formState: { errors, dirtyFields },
    register,
    handleSubmit,
    reset,
  } = form;

  useEffect(() => {
    if (!category) return;

    reset({
      name: category.name,
      slug: category.slug,
      parentId: category.parentId ?? undefined,
      description: category.description ?? undefined,
      logo: undefined,
      removeLogo: undefined,
    });
  }, [category, reset]);

  const handleFormSubmit = (values: CreateCategoryFormValues) => {
    if (category) {
      const dirtyValues = getDirtyValues<CreateCategoryFormValues>(
        dirtyFields as Partial<Record<keyof CreateCategoryFormValues, unknown>>,
        values,
      );

      if (!Object.keys(dirtyFields).length) {
        toast.info("No changes to save");
        return;
      }

      onSubmit(dirtyValues);
      return;
    }

    onSubmit(values);
  };

  return (
    <form
      onSubmit={handleSubmit(handleFormSubmit)}
      className="space-y-4"
      id="category-form"
    >
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Info size={16} /> Basic details
          </CardTitle>
        </CardHeader>
        <CardContent>
          <FieldGroup>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <Field>
                <RequiredFieldLabel htmlFor="name">
                  Category name
                </RequiredFieldLabel>

                <Input
                  id="name"
                  {...register("name")}
                  aria-invalid={!!errors.name}
                />

                <FieldError>{errors.name?.message}</FieldError>
              </Field>

              <AutoGeneratedSlugField form={form} />
            </div>

            <Controller
              control={form.control}
              name="parentId"
              render={({ field, fieldState }) => (
                <Field>
                  <FieldLabel htmlFor="parentId">
                    Parent category
                  </FieldLabel>

                  <Select
                    key={field.value}
                    name={field.name}
                    value={field.value}
                    onValueChange={field.onChange}
                  >
                    <SelectTrigger
                      id="parentId"
                      aria-invalid={fieldState.invalid}
                    >
                      <SelectValue placeholder="Select parent category" />
                    </SelectTrigger>

                    <SelectContent>
                      <SelectGroup>
                        {(parentCategories ?? []).map((pc) => (
                          <SelectItem key={pc.id} value={pc.id}>
                            {pc.name}
                          </SelectItem>
                        ))}
                      </SelectGroup>
                    </SelectContent>
                  </Select>

                  <FieldError>{errors.parentId?.message}</FieldError>
                </Field>
              )}
            />

            <Field>
              <FieldLabel htmlFor="description">Description</FieldLabel>

              <Controller
                control={form.control}
                name="description"
                render={({ field }) => (
                  <RichTextEditor
                    value={field.value ?? ""}
                    onChange={(value) => field.onChange(value ?? undefined)}
                    mediaItems={mediaItems}
                    isLoadingMediaItems={isLoadingMediaItems}
                    onFetchMediaItems={onFetchMediaItems}
                    onUploadMediaItems={onUploadMediaItems}
                    isUploadingMediaItems={isUploadingMediaItems}
                    onDeleteMediaItem={onDeleteMediaItem}
                    isDeletingMediaItem={isDeletingMediaItem}
                  />
                )}
              />

              <FieldError>{errors.description?.message}</FieldError>
            </Field>
          </FieldGroup>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <ImageIcon size={16} /> Media
          </CardTitle>
        </CardHeader>

        <CardContent>
          <LogoUploadField
            form={form}
            existingImage={category?.logo ?? undefined}
          />

          <FieldError>{errors.logo?.message}</FieldError>
        </CardContent>
      </Card>
    </form>
  );
}
