import { Controller, useFieldArray, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  Eye,
  Flame,
  ImageIcon,
  Info,
  LayoutGrid,
  Plus,
  SlidersVertical,
  Star,
  Trash2,
} from "lucide-react";
import { v4 as uuidv4 } from "uuid";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Field,
  FieldError,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { MultiSelect } from "@/components/MultiSelect";
import { RequiredFieldLabel } from "@/components/RequiredFieldLabel";
import { AutoGeneratedSlugField } from "@/components/forms/fields/AutoGeneratedSlugField";
import { LogoUploadField } from "@/components/forms/fields/LogoUploadField";
import { Category } from "@/features/categories/types";
import { Brand } from "@/features/brands/types";
import { capitalize } from "@/utils";
import { CreateProductFormValues, createProductSchema } from "../schemas";
import { ProductImageType, ProductStatus } from "../enums";
import { Button } from "@/components/ui/button";

interface ProductFormProps {
  onSubmit: (values: CreateProductFormValues) => void;
  defaultValues?: Partial<CreateProductFormValues>;
  isSubmitting?: boolean;
  categories: Category[];
  brands: Brand[];
}

export function ProductForm({
  onSubmit,
  defaultValues,
  categories,
  brands,
}: ProductFormProps) {
  const form = useForm({
    resolver: zodResolver(createProductSchema),
    defaultValues: {
      name: "",
      slug: "",
      brandId: "",
      categoryIds: [],
      status: ProductStatus.DRAFT,
      isFeatured: false,
      isBestseller: false,
      images: [],
      imageMetas: [],
      attributes: [],
      ...defaultValues,
    },
    mode: "all",
  });

  const { fields, append, remove } = useFieldArray({
    control: form.control,
    name: "attributes",
  });

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = form;

  const handleFormSubmit = (values: CreateProductFormValues) => {
    if (values.mainImage) {
      const uuid = uuidv4();
      const ext = values.mainImage.name.split(".").pop();
      const renamedMainImage = new File([values.mainImage], `${uuid}.${ext}`);
      values.images.push(renamedMainImage);
      values.imageMetas.push({
        imageType: ProductImageType.MAIN,
        altText: values.name,
        title: values.name,
      });
      delete values.mainImage;
    }

    values.attributes = values.attributes.map((attr, index) => ({
      ...attr,
      displayOrder: index,
    }));

    onSubmit(values);
  };

  return (
    <form
      onSubmit={handleSubmit(handleFormSubmit)}
      className="space-y-4"
      id="product-form"
    >
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Info size={16} /> Basic details
          </CardTitle>
        </CardHeader>
        <CardContent>
          <FieldGroup>
            <Field>
              <RequiredFieldLabel htmlFor="name">Name</RequiredFieldLabel>
              <Input
                id="name"
                {...register("name")}
                aria-invalid={!!errors.name}
              />
              <FieldError>{errors.name?.message}</FieldError>
            </Field>

            <AutoGeneratedSlugField form={form} />

            <Field>
              <FieldLabel htmlFor="shortDescription">
                Short description
              </FieldLabel>
              <Input id="shortDescription" {...register("shortDescription")} />
            </Field>

            <Field>
              <FieldLabel htmlFor="longDescription">
                Long description
              </FieldLabel>
              <Textarea
                id="longDescription"
                className="min-h-30"
                {...register("longDescription")}
              />
            </Field>
          </FieldGroup>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <LayoutGrid size={16} /> Brand & Categories
          </CardTitle>
        </CardHeader>

        <CardContent className="space-y-4">
          <Field>
            <RequiredFieldLabel htmlFor="brandId">Brand</RequiredFieldLabel>

            <Controller
              control={form.control}
              name="brandId"
              render={({ field }) => (
                <Select value={field.value} onValueChange={field.onChange}>
                  <SelectTrigger id="brandId" aria-invalid={!!errors.brandId}>
                    <SelectValue placeholder="Select brand" />
                  </SelectTrigger>

                  <SelectContent>
                    <SelectGroup>
                      {brands.map((brand) => (
                        <SelectItem key={brand.id} value={brand.id}>
                          {brand.name}
                        </SelectItem>
                      ))}
                    </SelectGroup>
                  </SelectContent>
                </Select>
              )}
            />

            <FieldError>{errors.brandId?.message}</FieldError>
          </Field>

          <Field>
            <RequiredFieldLabel>Categories</RequiredFieldLabel>

            <MultiSelect
              name="categoryIds"
              control={form.control}
              items={categories.map((category) => ({
                label: category.name,
                value: category.id,
              }))}
            />
          </Field>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Eye size={16} /> Status & Visibility
          </CardTitle>
        </CardHeader>

        <CardContent className="space-y-4">
          <div className="grid grid-cols-2 gap-2">
            <Field>
              <FieldLabel htmlFor="status">Status</FieldLabel>

              <Controller
                control={form.control}
                name="status"
                render={({ field }) => (
                  <Select value={field.value} onValueChange={field.onChange}>
                    <SelectTrigger id="status">
                      <SelectValue />
                    </SelectTrigger>

                    <SelectContent>
                      <SelectGroup>
                        {Object.values(ProductStatus).map((value) => (
                          <SelectItem key={value} value={value}>
                            {capitalize(value)}
                          </SelectItem>
                        ))}
                      </SelectGroup>
                    </SelectContent>
                  </Select>
                )}
              />
            </Field>
          </div>

          <div className="grid grid-cols-2 gap-2">
            <div className="bg-neutral-100 flex items-center justify-between p-6 gap-2 rounded-4xl">
              <div>
                <Star className="text-amber-300" />
              </div>

              <Field orientation="horizontal">
                <FieldLabel htmlFor="isFeatured">Featured</FieldLabel>
                <Controller
                  control={form.control}
                  name="isFeatured"
                  render={({ field }) => (
                    <Switch
                      checked={field.value}
                      onCheckedChange={field.onChange}
                    />
                  )}
                />
              </Field>
            </div>

            <div className="bg-neutral-100 flex items-center justify-between p-6 gap-2 rounded-4xl">
              <div>
                <Flame className="text-red-400" />
              </div>

              <Field orientation="horizontal">
                <FieldLabel htmlFor="isBestseller">Bestseller</FieldLabel>
                <Controller
                  control={form.control}
                  name="isBestseller"
                  render={({ field }) => (
                    <Switch
                      checked={field.value}
                      onCheckedChange={field.onChange}
                    />
                  )}
                />
              </Field>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <ImageIcon size={16} /> Product images
          </CardTitle>
        </CardHeader>

        <CardContent>
          <LogoUploadField
            form={form}
            fieldName="mainImage"
            label="Main image"
          />
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="flex items-center justify-between">
          <CardTitle className="flex items-center gap-2">
            <SlidersVertical size={16} /> Product attributes
          </CardTitle>

          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={() =>
              append({
                attributeKey: "",
                attributeKeyDisplay: "",
              })
            }
          >
            <Plus size={14} className="mr-1" />
            Add Attribute
          </Button>
        </CardHeader>

        <CardContent className="space-y-4">
          {fields.length === 0 && (
            <p className="text-sm text-center text-muted-foreground">
              No attributes added yet.
            </p>
          )}

          {fields.map((field, index) => (
            <div
              key={field.id}
              className="bg-neutral-100 p-4 rounded-3xl flex gap-4 items-center relative"
            >
              <div className="flex-1 grid grid-cols-2 gap-4">
                <Field>
                  <RequiredFieldLabel>Attribute key</RequiredFieldLabel>

                  <Input
                    {...register(`attributes.${index}.attributeKey` as const)}
                    placeholder="color"
                    aria-invalid={!!errors.attributes?.[index]?.attributeKey}
                    className="bg-white"
                  />

                  <FieldError>
                    {errors.attributes?.[index]?.attributeKey?.message}
                  </FieldError>
                </Field>

                <Field>
                  <RequiredFieldLabel>Attribute key display</RequiredFieldLabel>

                  <Input
                    {...register(
                      `attributes.${index}.attributeKeyDisplay` as const,
                    )}
                    placeholder="Color"
                    aria-invalid={
                      !!errors.attributes?.[index]?.attributeKeyDisplay
                    }
                    className="bg-white"
                  />

                  <FieldError>
                    {errors.attributes?.[index]?.attributeKeyDisplay?.message}
                  </FieldError>
                </Field>
              </div>

              <div className="w-6">
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  onClick={() => remove(index)}
                  className="text-muted-foreground absolute top-11 right-3"
                >
                  <Trash2 size={16} />
                </Button>
              </div>
            </div>
          ))}
        </CardContent>
      </Card>
    </form>
  );
}
