import { useEffect } from "react";
import { Controller, useFieldArray, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  Eye,
  Flame,
  ImageIcon,
  Info,
  LayoutGrid,
  Plus,
  SlidersVertical,
  Star,
  Trash2,
} from "lucide-react";
import { v4 as uuidv4 } from "uuid";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Field,
  FieldError,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { RichTextEditor } from "@/components/editor/RichTextEditor";
import { AutoGeneratedSlugField } from "@/components/forms/fields/AutoGeneratedSlugField";
import { MultiSelect } from "@/components/MultiSelect";
import { RequiredFieldLabel } from "@/components/RequiredFieldLabel";
import { Brand } from "@/features/brands/types";
import { Category } from "@/features/categories/types";
import { Media } from "@/features/media/types";
import { capitalize, getDirtyValues } from "@/utils";
import { CreateProductFormValues, createProductSchema } from "../schemas";
import { ProductImageType, ProductStatus } from "../enums";
import { Product } from "../types";
import { ProductGalleryManager } from "./ProductGalleryManager";

interface ProductFormProps {
  product?: Product | null;
  onSubmit: (values: Partial<CreateProductFormValues>) => void;
  isSubmitting?: boolean;
  categories: Category[];
  brands: Brand[];
  mediaItems?: Media[];
  isLoadingMediaItems?: boolean;
  onFetchMediaItems?: () => void;
  onUploadMediaItems?: (files: File[]) => void;
  isUploadingMediaItems?: boolean;
  onDeleteMediaItem?: (id: string) => void;
  isDeletingMediaItem?: boolean;
}

const DEFAULT_VALUES: CreateProductFormValues = {
  name: "",
  slug: "",
  brandId: "",
  categoryIds: [],
  status: ProductStatus.DRAFT,
  isFeatured: false,
  isBestseller: false,
  images: [],
  imageMetas: [],
  attributes: [],
};

export function ProductForm({
  product,
  onSubmit,
  categories,
  brands,
  mediaItems,
  onFetchMediaItems,
  isLoadingMediaItems,
  onUploadMediaItems,
  isUploadingMediaItems,
  onDeleteMediaItem,
  isDeletingMediaItem,
}: ProductFormProps) {
  const form = useForm({
    resolver: zodResolver(createProductSchema),
    defaultValues: DEFAULT_VALUES,
    mode: "all",
  });

  const { fields, append, remove } = useFieldArray({
    control: form.control,
    name: "attributes",
  });

  const {
    register,
    handleSubmit,
    formState: { errors, dirtyFields },
    trigger,
    reset,
  } = form;

  useEffect(() => {
    if (!product || !brands.length || !categories.length) return;

    reset({
      name: product.name,
      slug: product.slug,
      shortDescription: product.shortDescription ?? undefined,
      longDescription: product.longDescription ?? undefined,
      brandId: product.brand.id,
      categoryIds: product.categories.map((cat) => cat.id),
      status: product.status,
      isFeatured: product.isFeatured,
      isBestseller: product.isBestseller,
      attributes: product.attributes,
      gallery: product.images.map((img) => ({
        id: img.id,
        preview: img.url,
        url: img.url,
        file: undefined,
        isMain: img.imageType === ProductImageType.MAIN,
        altText: img.altText ?? "",
      })),
    });
  }, [product, brands, categories, reset]);

  const handleFormSubmit = (values: CreateProductFormValues) => {
    let dirtyValues: Partial<CreateProductFormValues> = {};

    if (product) {
      dirtyValues = getDirtyValues<CreateProductFormValues>(
        dirtyFields as Partial<Record<keyof CreateProductFormValues, unknown>>,
        values,
      );

      if (!Object.keys(dirtyFields).length) return;
    }

    if (values.mainImage) {
      const uuid = uuidv4();
      const ext = values.mainImage.name.split(".").pop();
      const renamedMainImage = new File([values.mainImage], `${uuid}.${ext}`);
      values.images.push(renamedMainImage);
      values.imageMetas.push({
        imageType: ProductImageType.MAIN,
        altText: values.name,
        title: values.name,
      });
      delete values.mainImage;
    }

    values = {
      ...values,
      ...dirtyValues,
    };

    values.attributes = values.attributes.map((attr, index) => ({
      ...attr,
      displayOrder: index,
    }));

    (values.gallery || []).forEach((img, index) => {
      if (img.file) {
        const ext = img.file.name.split(".").pop();
        const renamedMainImage = new File([img.file], `${img.id}.${ext}`);
        values.images.push(renamedMainImage);
      }

      values.imageMetas.push({
        id: img.id,
        imageType: img.isMain
          ? ProductImageType.MAIN
          : ProductImageType.GALLERY,
        altText: img.altText || "",
        title: "",
        displayOrder: index,
        isDeleted: img.isDeleted,
      });
    });

    delete values.gallery;

    onSubmit(values);
  };

  return (
    <form
      onSubmit={handleSubmit(handleFormSubmit)}
      className="space-y-4"
      id="product-form"
    >
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Info size={16} /> Basic details
          </CardTitle>
        </CardHeader>
        <CardContent>
          <FieldGroup>
            <Field>
              <RequiredFieldLabel htmlFor="name">Name</RequiredFieldLabel>
              <Input
                id="name"
                {...register("name")}
                aria-invalid={!!errors.name}
              />
              <FieldError>{errors.name?.message}</FieldError>
            </Field>

            <AutoGeneratedSlugField form={form} />

            <Field>
              <FieldLabel htmlFor="shortDescription">
                Short description
              </FieldLabel>
              <Input id="shortDescription" {...register("shortDescription")} />
            </Field>

            <Field>
              <FieldLabel htmlFor="longDescription">
                Long description
              </FieldLabel>
              <Controller
                control={form.control}
                name="longDescription"
                render={({ field }) => (
                  <RichTextEditor
                    value={field.value}
                    onChange={field.onChange}
                    mediaItems={mediaItems}
                    isLoadingMediaItems={isLoadingMediaItems}
                    onFetchMediaItems={onFetchMediaItems}
                    onUploadMediaItems={onUploadMediaItems}
                    isUploadingMediaItems={isUploadingMediaItems}
                    onDeleteMediaItem={onDeleteMediaItem}
                    isDeletingMediaItem={isDeletingMediaItem}
                  />
                )}
              />
            </Field>
          </FieldGroup>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <LayoutGrid size={16} /> Brand & Categories
          </CardTitle>
        </CardHeader>

        <CardContent className="space-y-4">
          <Controller
            control={form.control}
            name="brandId"
            render={({ field, fieldState }) => (
              <Field>
                <RequiredFieldLabel htmlFor="brandId">Brand</RequiredFieldLabel>

                <Select
                  key={field.value}
                  name={field.name}
                  value={field.value}
                  onValueChange={field.onChange}
                >
                  <SelectTrigger id="brandId" aria-invalid={fieldState.invalid}>
                    <SelectValue placeholder="Select brand" />
                  </SelectTrigger>

                  <SelectContent>
                    <SelectGroup>
                      {brands.map((brand) => (
                        <SelectItem key={brand.id} value={brand.id}>
                          {brand.name}
                        </SelectItem>
                      ))}
                    </SelectGroup>
                  </SelectContent>
                </Select>
                <FieldError>{errors.brandId?.message}</FieldError>
              </Field>
            )}
          />

          <Field>
            <RequiredFieldLabel>Categories</RequiredFieldLabel>

            <MultiSelect
              name="categoryIds"
              control={form.control}
              items={categories.map((category) => ({
                label: category.name,
                value: category.id,
              }))}
            />
          </Field>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Eye size={16} /> Status & Visibility
          </CardTitle>
        </CardHeader>

        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            <Controller
              name="status"
              control={form.control}
              render={({ field }) => (
                <Field>
                  <FieldLabel htmlFor="status">Status</FieldLabel>

                  <Select
                    key={field.value}
                    name={field.name}
                    value={field.value}
                    onValueChange={field.onChange}
                  >
                    <SelectTrigger id="status" className="w-full">
                      <SelectValue />
                    </SelectTrigger>

                    <SelectContent>
                      <SelectGroup>
                        {Object.values(ProductStatus).map((value) => (
                          <SelectItem key={value} value={value}>
                            {capitalize(value)}
                          </SelectItem>
                        ))}
                      </SelectGroup>
                    </SelectContent>
                  </Select>
                </Field>
              )}
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div className="bg-neutral-100 flex items-center justify-between p-4 sm:p-6 gap-3 rounded-2xl sm:rounded-4xl">
              <Star className="text-amber-300 shrink-0" />

              <Field
                orientation="horizontal"
                className="w-full justify-between"
              >
                <FieldLabel htmlFor="isFeatured">Featured</FieldLabel>
                <Controller
                  control={form.control}
                  name="isFeatured"
                  render={({ field }) => (
                    <Switch
                      checked={field.value}
                      onCheckedChange={field.onChange}
                    />
                  )}
                />
              </Field>
            </div>

            <div className="bg-neutral-100 flex items-center justify-between p-4 sm:p-6 gap-3 rounded-2xl sm:rounded-4xl">
              <Flame className="text-red-400 shrink-0" />

              <Field
                orientation="horizontal"
                className="w-full justify-between"
              >
                <FieldLabel htmlFor="isBestseller">Bestseller</FieldLabel>
                <Controller
                  control={form.control}
                  name="isBestseller"
                  render={({ field }) => (
                    <Switch
                      checked={field.value}
                      onCheckedChange={field.onChange}
                    />
                  )}
                />
              </Field>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <ImageIcon size={16} /> Product images
          </CardTitle>
        </CardHeader>

        <CardContent>
          <Controller
            control={form.control}
            name="gallery"
            defaultValue={[]}
            render={({ field }) => (
              <ProductGalleryManager
                value={field.value || []}
                onChange={field.onChange}
              />
            )}
          />
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="flex items-center justify-between">
          <CardTitle className="flex items-center gap-2">
            <SlidersVertical size={16} /> Product attributes
          </CardTitle>

          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={() =>
              append({
                attributeKey: "",
                attributeKeyDisplay: "",
              })
            }
          >
            <Plus size={14} className="mr-1" />
            Add Attribute
          </Button>
        </CardHeader>

        <CardContent className="space-y-4">
          {fields.length === 0 && (
            <p className="text-sm text-center text-muted-foreground">
              No attributes added yet.
            </p>
          )}

          {fields.map((field, index) => (
            <div
              key={field.id}
              className="bg-neutral-100 p-4 sm:p-5 rounded-3xl flex flex-col gap-4 relative"
            >
              <Button
                type="button"
                variant="ghost"
                size="icon"
                onClick={() => remove(index)}
                className="absolute top-3 right-3 text-red-500"
              >
                <Trash2 size={16} />
              </Button>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <Field>
                  <RequiredFieldLabel>Attribute key</RequiredFieldLabel>

                  <Input
                    {...register(`attributes.${index}.attributeKey` as const, {
                      onChange: () => {
                        fields.forEach((_, i) =>
                          trigger(`attributes.${i}.attributeKey`),
                        );
                      },
                    })}
                    placeholder="color"
                    aria-invalid={!!errors.attributes?.[index]?.attributeKey}
                    className="bg-white"
                  />

                  <FieldError>
                    {errors.attributes?.[index]?.attributeKey?.message}
                  </FieldError>
                </Field>

                <Field>
                  <RequiredFieldLabel>Attribute key display</RequiredFieldLabel>

                  <Input
                    {...register(
                      `attributes.${index}.attributeKeyDisplay` as const,
                    )}
                    placeholder="Color"
                    aria-invalid={
                      !!errors.attributes?.[index]?.attributeKeyDisplay
                    }
                    className="bg-white"
                  />

                  <FieldError>
                    {errors.attributes?.[index]?.attributeKeyDisplay?.message}
                  </FieldError>
                </Field>
              </div>
            </div>
          ))}
        </CardContent>
      </Card>
    </form>
  );
}
