"use client";

import { ImageIcon, Info } from "lucide-react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";

import {
  Field,
  FieldError,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { RequiredFieldLabel } from "@/components/RequiredFieldLabel";
import { AutoGeneratedSlugField } from "@/components/forms/fields/AutoGeneratedSlugField";
import { LogoUploadField } from "@/components/forms/fields/LogoUploadField";
import {
  CreateBrandFormValues,
  createBrandSchema,
} from "@/features/brands/schemas";

interface BrandFormProps {
  onSubmit: (values: CreateBrandFormValues) => void;
  defaultValues?: Partial<CreateBrandFormValues>;
  isSubmitting?: boolean;
}

export function BrandForm({ onSubmit, defaultValues }: BrandFormProps) {
  const form = useForm<CreateBrandFormValues>({
    resolver: zodResolver(createBrandSchema),
    defaultValues,
    mode: "all",
  });

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = form;

  return (
    <form
      onSubmit={handleSubmit(onSubmit)}
      className="space-y-4"
      id="brand-form"
    >
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Info size={16} /> Basic details
          </CardTitle>
        </CardHeader>
        <CardContent>
          <FieldGroup>
            <div className="grid grid-cols-2 gap-4">
              <Field>
                <RequiredFieldLabel htmlFor="name">
                  Brand name
                </RequiredFieldLabel>
                <Input
                  id="name"
                  {...register("name")}
                  aria-invalid={!!errors.name}
                />
                <FieldError>{errors.name?.message}</FieldError>
              </Field>

              <AutoGeneratedSlugField form={form} />
            </div>

            <Field>
              <FieldLabel htmlFor="description">Description</FieldLabel>
              <Textarea
                id="description"
                className="min-h-30"
                {...register("description")}
              />
            </Field>
          </FieldGroup>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <ImageIcon size={16} /> Media
          </CardTitle>
        </CardHeader>

        <CardContent>
          <LogoUploadField form={form} />
        </CardContent>
      </Card>
    </form>
  );
}
