"use client";

import { useEffect } from "react";
import { ImageIcon, Info } from "lucide-react";
import { Controller, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Field,
  FieldError,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { RequiredFieldLabel } from "@/components/RequiredFieldLabel";
import { AutoGeneratedSlugField } from "@/components/forms/fields/AutoGeneratedSlugField";
import { LogoUploadField } from "@/components/forms/fields/LogoUploadField";
import { RichTextEditor } from "@/components/editor/RichTextEditor";
import {
  CreateBrandFormValues,
  createBrandSchema,
} from "@/features/brands/schemas";
import { Brand } from "../types";
import { getDirtyValues } from "@/utils/forms";

interface BrandFormProps {
  brand?: Brand;
  isSubmitting?: boolean;
  onSubmit: (values: Partial<CreateBrandFormValues>) => void;
}

const DEFAULT_VALUES: CreateBrandFormValues = {
  name: "",
  slug: "",
  description: undefined,
  logo: undefined,
  removeLogo: undefined,
};

export function BrandForm({ onSubmit, brand }: BrandFormProps) {
  const form = useForm<CreateBrandFormValues>({
    resolver: zodResolver(createBrandSchema),
    defaultValues: DEFAULT_VALUES,
    mode: "all",
  });

  const {
    formState: { errors, dirtyFields },
    handleSubmit,
    register,
    reset,
  } = form;

  useEffect(() => {
    if (!brand) {
      reset(DEFAULT_VALUES);
      return;
    }

    reset({
      name: brand.name,
      slug: brand.slug,
      description: brand.description ?? undefined,
      logo: undefined,
      removeLogo: undefined,
    });
  }, [brand, reset]);

  const handleFormSubmit = (values: CreateBrandFormValues) => {
    if (brand) {
      const dirtyValues = getDirtyValues<CreateBrandFormValues>(
        dirtyFields as Partial<Record<keyof CreateBrandFormValues, unknown>>,
        values,
      );

      if (!Object.keys(dirtyFields).length) return;

      onSubmit(dirtyValues);
      return;
    }

    onSubmit(values);
  };

  return (
    <form
      onSubmit={handleSubmit(handleFormSubmit)}
      className="space-y-4"
      id="brand-form"
    >
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Info size={16} /> Basic details
          </CardTitle>
        </CardHeader>

        <CardContent>
          <FieldGroup>
            <div className="grid grid-cols-2 gap-4">
              <Field>
                <RequiredFieldLabel htmlFor="name">
                  Brand name
                </RequiredFieldLabel>

                <Input
                  id="name"
                  {...register("name")}
                  aria-invalid={!!errors.name}
                />

                <FieldError>{errors.name?.message}</FieldError>
              </Field>

              <AutoGeneratedSlugField form={form} />
            </div>

            <Field>
              <FieldLabel htmlFor="description">Description</FieldLabel>

              <Controller
                control={form.control}
                name="description"
                render={({ field }) => (
                  <RichTextEditor
                    value={field.value ?? ""}
                    onChange={(value) => field.onChange(value ?? "")}
                  />
                )}
              />

              <FieldError>{errors.description?.message}</FieldError>
            </Field>
          </FieldGroup>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <ImageIcon size={16} /> Media
          </CardTitle>
        </CardHeader>

        <CardContent>
          <LogoUploadField
            form={form}
            existingImage={brand?.logo ?? undefined}
          />

          <FieldError>{errors.logo?.message}</FieldError>
        </CardContent>
      </Card>
    </form>
  );
}
