import { useEffect, useRef } from "react";
import { FieldValues, Path, PathValue, UseFormReturn } from "react-hook-form";
import { RefreshCw } from "lucide-react";

import { Field, FieldError } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { RequiredFieldLabel } from "@/components/RequiredFieldLabel";
import { slugify } from "@/utils";

interface AutoGeneratedSlugFieldProps<T extends FieldValues> {
  form: UseFormReturn<T>;
  sourceField?: Path<T>;
  slugField?: Path<T>;
  label?: string;
}

export function AutoGeneratedSlugField<T extends FieldValues>({
  form,
  sourceField = "name" as Path<T>,
  slugField = "slug" as Path<T>,
  label = "Slug",
}: AutoGeneratedSlugFieldProps<T>) {
  const slugTouchedRef = useRef(false);
  const {
    register,
    setValue,
    formState: { errors },
    watch,
  } = form;

  const name = watch(sourceField);

  useEffect(() => {
    if (!slugTouchedRef.current) {
      const slugValue = slugify(name ?? "") as PathValue<T, Path<T>>;
      setValue(slugField, slugValue, {
        shouldDirty: true,
        shouldValidate: !!name?.trim(),
      });
    }
  }, [name, setValue, slugTouchedRef, slugField]);

  const handleRegenerateSlug = () => {
    const regenerated = slugify(name ?? "");

    if (!regenerated) return;

    slugTouchedRef.current = false;

    const slugValue = regenerated as PathValue<T, Path<T>>;
    setValue(slugField, slugValue, {
      shouldDirty: true,
      shouldValidate: true,
    });
  };

  const slugError = errors[slugField];

  const { onChange: rhfOnChange, ...slugRegistration } = register(slugField);

  return (
    <Field>
      <RequiredFieldLabel htmlFor={slugField}>{label}</RequiredFieldLabel>

      <div className="relative">
        <Input
          id={slugField}
          {...slugRegistration}
          onChange={(e) => {
            slugTouchedRef.current = true;
            rhfOnChange(e);
          }}
          aria-invalid={!!slugError}
        />

        <Tooltip>
          <TooltipTrigger asChild>
            <button
              type="button"
              onClick={handleRegenerateSlug}
              className="absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition"
              title="Regenerate slug"
            >
              <RefreshCw size={16} />
            </button>
          </TooltipTrigger>
          <TooltipContent>Regenerate from {sourceField}</TooltipContent>
        </Tooltip>
      </div>

      <FieldError>{slugError?.message as string}</FieldError>
    </Field>
  );
}
