import { useEffect } from "react";
import { UseFormReturn } from "react-hook-form";
import { RefreshCw } from "lucide-react";

import { Field, FieldError } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { RequiredFieldLabel } from "@/components/RequiredFieldLabel";
import { CreateCategoryFormValues } from "@/features/categories/schemas";
import { slugify } from "@/utils";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";

interface AutoGeneratedSlugFieldProps {
  form: UseFormReturn<CreateCategoryFormValues>;
  slugTouchedRef: React.RefObject<boolean>;
}

export function AutoGeneratedSlugField({
  form,
  slugTouchedRef,
}: AutoGeneratedSlugFieldProps) {
  const {
    register,
    setValue,
    formState: { errors },
    watch,
  } = form;

  const name = watch("name");

  useEffect(() => {
    if (!slugTouchedRef.current) {
      setValue("slug", slugify(name ?? ""), {
        shouldDirty: true,
        shouldValidate: !!name?.trim(),
      });
    }
  }, [name, setValue, slugTouchedRef]);

  return (
    <Field>
      <RequiredFieldLabel htmlFor="slug">Slug</RequiredFieldLabel>

      <div className="relative">
        <Input
          id="slug"
          {...register("slug")}
          onChange={() => (slugTouchedRef.current = true)}
        />

        <Tooltip>
          <TooltipTrigger asChild>
            <button
              type="button"
              onClick={() => {
                const regenerated = slugify(name ?? "");

                if (!regenerated) return;

                slugTouchedRef.current = false;

                setValue("slug", regenerated, {
                  shouldDirty: true,
                  shouldValidate: true,
                });
              }}
              className="absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition"
              title="Regenerate slug"
            >
              <RefreshCw size={16} />
            </button>
          </TooltipTrigger>
          <TooltipContent>Regenerate from name</TooltipContent>
        </Tooltip>
      </div>

      <FieldError>{errors.slug?.message}</FieldError>
    </Field>
  );
}
